/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPostDispatchHook,
  IPostDispatchHookInterface,
} from "../../../../../../@hyperlane-xyz/core/contracts/interfaces/hooks/IPostDispatchHook";

const _abi = [
  {
    inputs: [],
    name: "hookType",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "metadata",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
    ],
    name: "postDispatch",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "metadata",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
    ],
    name: "quoteDispatch",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "metadata",
        type: "bytes",
      },
    ],
    name: "supportsMetadata",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPostDispatchHook__factory {
  static readonly abi = _abi;
  static createInterface(): IPostDispatchHookInterface {
    return new Interface(_abi) as IPostDispatchHookInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPostDispatchHook {
    return new Contract(address, _abi, runner) as unknown as IPostDispatchHook;
  }
}
