/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../../common";

export interface IPostDispatchHookInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "hookType"
      | "postDispatch"
      | "quoteDispatch"
      | "supportsMetadata"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "hookType", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "postDispatch",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "quoteDispatch",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsMetadata",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "hookType", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "postDispatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quoteDispatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsMetadata",
    data: BytesLike
  ): Result;
}

export interface IPostDispatchHook extends BaseContract {
  connect(runner?: ContractRunner | null): IPostDispatchHook;
  waitForDeployment(): Promise<this>;

  interface: IPostDispatchHookInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  hookType: TypedContractMethod<[], [bigint], "view">;

  postDispatch: TypedContractMethod<
    [metadata: BytesLike, message: BytesLike],
    [void],
    "payable"
  >;

  quoteDispatch: TypedContractMethod<
    [metadata: BytesLike, message: BytesLike],
    [bigint],
    "view"
  >;

  supportsMetadata: TypedContractMethod<
    [metadata: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "hookType"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "postDispatch"
  ): TypedContractMethod<
    [metadata: BytesLike, message: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "quoteDispatch"
  ): TypedContractMethod<
    [metadata: BytesLike, message: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "supportsMetadata"
  ): TypedContractMethod<[metadata: BytesLike], [boolean], "view">;

  filters: {};
}
