/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISpecifiesInterchainSecurityModule,
  ISpecifiesInterchainSecurityModuleInterface,
} from "../../../../../../@hyperlane-xyz/core/contracts/interfaces/IInterchainSecurityModule.sol/ISpecifiesInterchainSecurityModule";

const _abi = [
  {
    inputs: [],
    name: "interchainSecurityModule",
    outputs: [
      {
        internalType: "contract IInterchainSecurityModule",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ISpecifiesInterchainSecurityModule__factory {
  static readonly abi = _abi;
  static createInterface(): ISpecifiesInterchainSecurityModuleInterface {
    return new Interface(_abi) as ISpecifiesInterchainSecurityModuleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISpecifiesInterchainSecurityModule {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ISpecifiesInterchainSecurityModule;
  }
}
