/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface Poseidon2TestInterface extends Interface {
  getFunction(
    nameOrSignature: "hash_1" | "hash_1_twice" | "hash_2" | "hash_3"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "hash_1",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hash_1_twice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hash_2",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hash_3",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "hash_1", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hash_1_twice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hash_2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hash_3", data: BytesLike): Result;
}

export interface Poseidon2Test extends BaseContract {
  connect(runner?: ContractRunner | null): Poseidon2Test;
  waitForDeployment(): Promise<this>;

  interface: Poseidon2TestInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  hash_1: TypedContractMethod<[m1: BigNumberish], [bigint], "view">;

  hash_1_twice: TypedContractMethod<[m1: BigNumberish], [bigint], "view">;

  hash_2: TypedContractMethod<
    [m1: BigNumberish, m2: BigNumberish],
    [bigint],
    "view"
  >;

  hash_3: TypedContractMethod<
    [m1: BigNumberish, m2: BigNumberish, m3: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "hash_1"
  ): TypedContractMethod<[m1: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "hash_1_twice"
  ): TypedContractMethod<[m1: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "hash_2"
  ): TypedContractMethod<
    [m1: BigNumberish, m2: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "hash_3"
  ): TypedContractMethod<
    [m1: BigNumberish, m2: BigNumberish, m3: BigNumberish],
    [bigint],
    "view"
  >;

  filters: {};
}
